#pragma once
#include <string_view>
#include <vector>
#include <algorithm>
#include <cstddef>
#include <stdexcept>

namespace MemoryEngine {
    
    // represents a single structural field descriptor
    struct StructMember {
        std::string_view name;
        size_t size;
        size_t alignment;
    };

    // diagnotic analysis generated by the engine
    struct LayoutReport {
        size_t total_size{0};
        size_t total_padding{0};
        size_t max_alignment_boundary{1};
        std::vector<size_t> computed_offsets;
    };

    class StructOptimizer {
        public:
            static LayoutReport evaluate_layout (const std::vector<StructMember>& members) {
                LayoutReport report;
                report.computed_offsets.reserve(members.size());

                size_t current_offset = 0;
                size_t max_align = 1;

                for (const auto& member : members) {
                    if (member.alignment == 0UZ) {
                        throw std::invalid_argument("StructMember alignment must be non-zero");
                    }
                    max_align = std::max(max_align, member.alignment);
                    
                    // determining the compiler padding bytes required to align this specific field
                    size_t padding_needed = 0;
                    if (current_offset % member.alignment != 0) {
                        padding_needed = member.alignment - (current_offset % member.alignment); 
                    }

                    report.total_padding += padding_needed;
                    current_offset += padding_needed;

                    report.computed_offsets.push_back(current_offset);
                    current_offset += member.size;
                }

                // for tail_padding the entire struct after all members 
                size_t tail_padding = 0;
                if (current_offset % max_align != 0) {
                    tail_padding = max_align - (current_offset % max_align);
                }

                report.total_padding += tail_padding;
                current_offset += tail_padding;

                report.total_size = current_offset;
                report.max_alignment_boundary = max_align;

                return report;
            }
        
            static std::vector<StructMember> optimize_layout(std::vector<StructMember> members) noexcept {
                std::sort(members.begin(), members.end(), 
                        [](const StructMember& lhs, const StructMember& rhs) noexcept {
                            if (lhs.alignment != rhs.alignment) {
                                return lhs.alignment > rhs.alignment;
                            }
                            return lhs.size > rhs.size; 
                        }
                );
                return members;                
            }

    };


}